# Generated by Django 5.1.1 on 2024-10-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion',
        ),
    ]
