# Generated by Django 5.1.1 on 2024-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_remove_usuario_es_admin_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('administrador', 'Administrador'), ('gestion', 'Gestión')], default='comprador', max_length=20),
        ),
    ]
