# Generated by Django 5.1.1 on 2024-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('administrador', 'Administrador'), ('gestor', 'Gestor')], default='comprador', max_length=20),
        ),
    ]
