# Generated by Django 5.0.6 on 2024-10-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Prenda',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('tamano', models.CharField(max_length=4)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('slug', models.SlugField(default='')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo_prenda')),
            ],
        ),
    ]
