# Generated by Django 5.1.1 on 2024-10-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca_id',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo_id',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario_id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
