# Generated by Django 5.1.1 on 2024-10-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_marca_id_producto_marca_and_more'),
        ('usuario', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='marca_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='tipo_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Reacondicionado', 'Reacondicionado'), ('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
    ]
