# Generated by Django 5.1.1 on 2024-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_marca_producto_marca_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_ofertado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
