# Generated by Django 5.1.1 on 2024-10-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_precio_ofertado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/fotos/')),
                ('slug', models.SlugField(blank=True, default='')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.ManyToManyField(blank=True, to='productos.imagen'),
        ),
    ]
