# Generated by Django 5.1.1 on 2024-10-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_imagen_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='slug',
        ),
    ]
