# Generated by Django 5.1.1 on 2024-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_imagen_descripcion_remove_imagen_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
