# Generated by Django 5.1.1 on 2024-10-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_producto_imagenes_producto_descripcion_and_more'),
        ('tiendas', '0005_alter_tienda_tienda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda'),
            preserve_default=False,
        ),
    ]
