# Generated by Django 5.1.1 on 2024-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_producto_usuario_id_producto_tienda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_ofertado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
