# Generated by Django 5.1.1 on 2024-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_precio_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_ofertado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
