# Generated by Django 5.1.1 on 2024-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_producto_precio_ofertado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_ofertado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
