# Generated by Django 5.1.1 on 2024-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_remove_producto_precio_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4),
        ),
    ]
