# Generated by Django 5.1.1 on 2024-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subastado',
            field=models.BooleanField(default=False),
        ),
    ]
