# Generated by Django 5.1.1 on 2024-10-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='ruc_cif_nit',
            new_name='rut',
        ),
    ]
