# Generated by Django 5.1.1 on 2024-10-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_rename_ruc_cif_nit_tienda_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='sitio_web',
        ),
    ]
