# Generated by Django 5.1.1 on 2024-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_remove_tienda_sitio_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='id',
        ),
        migrations.AddField(
            model_name='tienda',
            name='password',
            field=models.CharField(default=123123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='tienda_id',
            field=models.AutoField(primary_key=True, serialize=False, auto_created=True),
            preserve_default=False,
        ),
    ]
