# Generated by Django 5.1.1 on 2024-10-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0004_remove_tienda_id_tienda_password_tienda_tienda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='tienda_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
