# Generated by Django 5.1.1 on 2024-10-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0006_alter_tienda_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='tamano_empresa',
        ),
    ]
