# Generated by Django 5.1.1 on 2024-10-20 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_producto_usuario_id_producto_tienda_id'),
        ('tiendas', '0008_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
