# Generated by Django 5.1.1 on 2024-10-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0009_alter_bodega_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
    ]
