# Generated by Django 5.1.1 on 2024-11-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0010_tienda_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='tienda',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
