# Generated by Django 5.1.1 on 2024-10-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
