# Generated by Django 5.1.1 on 2024-10-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_subasta_tienda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subasta',
            name='precio_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subasta',
            name='precio_ofertado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
