# Generated by Django 5.1.1 on 2024-10-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_subasta_descripcion_subasta_precio_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='descripcion',
        ),
    ]
