# Generated by Django 5.1.1 on 2024-10-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_subasta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='precio_inicial',
        ),
        migrations.RemoveField(
            model_name='subasta',
            name='precio_ofertado',
        ),
    ]
