# Generated by Django 5.1.1 on 2024-10-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_subasta_precio_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='precio_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subasta',
            name='precio_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puja',
            name='subasta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puja_set', to='compras.subasta'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='vigente', max_length=20),
        ),
    ]
