# Generated by Django 5.1.1 on 2024-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_subasta_precio_final_subasta_precio_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_termino',
            field=models.DateTimeField(),
        ),
    ]
