# Generated by Django 5.1.1 on 2024-10-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_subasta_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subasta',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='subasta',
            old_name='tienda_id',
            new_name='tienda',
        ),
    ]
