# Generated by Django 5.1.1 on 2024-10-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_puja_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='puja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.puja'),
        ),
    ]
