# Generated by Django 5.1.1 on 2024-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_transaccion_puja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
