# Generated by Django 5.1.1 on 2024-11-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='puja_id',
        ),
        migrations.AddField(
            model_name='subasta',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subasta', to='compras.transaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='puja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.puja'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
