# Generated by Django 5.1.1 on 2024-11-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_remove_transaccion_puja_id_subasta_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='puja',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compras.puja'),
        ),
    ]
