# Generated by Django 5.1.1 on 2024-11-08 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_alter_transaccion_puja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='transaccion',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='puja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.puja'),
        ),
    ]
