# Generated by Django 5.1.1 on 2024-11-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_remove_subasta_transaccion_alter_transaccion_puja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='puja',
            new_name='puja_id',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
