# Generated by Django 5.1.1 on 2024-11-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_alter_transaccion_estado'),
        ('compras', '0020_rename_puja_transaccion_puja_id_and_more'),
    ]

    operations = [
    ]
